---
# tasks/main.yml

- name: Install dependencies
  apt:
    name:
      - wget
      - tar
      - curl
    state: present
  become: true

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Move Prometheus binaries to /usr/local/bin/
  command: mv /usr/local/bin/prometheus-{{ prometheus_version }}.linux-amd64/prometheus /usr/local/bin/prometheus creates=/usr/local/bin/prometheus

- name: Move Promtool binary to /usr/local/bin/
  command: mv /usr/local/bin/prometheus-{{ prometheus_version }}.linux-amd64/promtool /usr/local/bin/promtool creates=/usr/local/bin/promtool

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory

- name: Copy Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Create a systemd service file for Prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring System
      After=network.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/data \
        --web.listen-address="0.0.0.0:9090"
        
      [Install]
      WantedBy=multi-user.target

- name: Start and enable Prometheus service
  systemd:
    name: prometheus.service
    state: started
    enabled: true