- name: Create a new user test_user2
  hosts: slaves
  become: yes  # Используйте sudo для выполнения задач от имени администратора
  tasks:
    - name: Ensure the user is present
      user:
        name: test_user2          # Имя пользователя, которого нужно создать
        state: present         # Убедитесь, что пользователь существует
        shell: /bin/bash       # Укажите оболочку (по умолчанию /bin/bash)

- name: Create a directory app
  hosts: slaves
  become: yes  # Используйте sudo, если необходимо
  tasks:
    - name: Ensure the directory exists
      file:
        path: /app/  # Укажите путь к создаваемой директории
        state: directory          # Указывает, что нужно создать директорию
        owner: test_user2          # Укажите владельца директории (опционально)
        group: root         # Укажите группу директории (опционально)
        mode: '0640'              # Установите права доступа (опционально)
    - name: Create file
      file:
        path: /app/config.txt
        state: touch
        owner: test_user2          # Укажите владельца директории (опционально)
        group: test_user2         # Укажите группу директории (опционально)
        mode: '0640'              # Установите права доступа (опционально)
    - name: Text in file
      copy:
        content: "This is test file"
        dest: /app/config.txt

- name: Install packages on remote hosts
  hosts: slaves
  become: yes  # Используйте sudo, если необходимо
  tasks:
    - name: Install dump
      apt:
        name: tcpdump
        state: present