---
- name: Create a user and deploy SSH key
  hosts: slaves
  become: yes  # Используйте sudo для выполнения задач от имени администратора
  vars:
    username: user  # Замените на имя пользователя, которого хотите создать
    ssh_key: "{{ lookup('file', '/path/to/file') }}"  # Укажите путь к вашему публичному ключу
    user_password: "your_password"  # Замените на желаемый пароль для пользователя

  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        state: present
        create_home: yes  # Создать домашнюю директорию
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo  # Добавляем пользователя в группу sudo
        append: yes  # Не удалять пользователя из других групп

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'  # Права доступа к директории .ssh

    - name: Deploy SSH public key
      copy:
        content: "{{ ssh_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'  # Права доступа к файлу authorized_keys